# Generated by Django 4.2.2 on 2023-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optytracker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
