# Generated by Django 4.2.1 on 2023-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtest', '0002_alter_accelerator_id_alter_optytracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='optytracker',
            name='accelerators',
            field=models.ManyToManyField(through='modtest.OptyAcc', to='modtest.accelerator'),
        ),
    ]
