# Generated by Django 4.2.1 on 2023-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtest', '0003_optytracker_accelerators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='optyacc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='optytracker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='optytracker',
            name='op_id',
            field=models.IntegerField(unique=True),
        ),
    ]
