# Generated by Django 4.2.2 on 2023-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtest', '0004_alter_accelerator_id_alter_optyacc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optytracker',
            name='op_id',
            field=models.IntegerField(),
        ),
    ]
